WITH OSCHEMAS AS
    (select PATH, SCHEMA, ordercols(SCHEMA) OSCHEMA FROM SCHEMAS),
SUPERSETS AS
    (SELECT o1.PATH PATH, o1.SCHEMA O1SCHEMA, o1.OSCHEMA O1OSCHEMA, o2.SCHEMA O2SCHEMA, o2.OSCHEMA O2OSCHEMA  FROM OSCHEMAS o1 CROSS JOIN OSCHEMAS o2
        WHERE o1.OSCHEMA LIKE CONCAT(o2.OSCHEMA, '%') AND o1.OSCHEMA != o2.OSCHEMA),
SCHEMAS_2ND AS
   (SELECT string(COLLECT_LIST(CONCAT(PATH, "|"))) PATH, O1OSCHEMA SCHEMA FROM SUPERSETS s GROUP BY O1OSCHEMA),
OSCHEMAS_2ND AS
    (select PATH, SCHEMA, ordercols(SCHEMA) OSCHEMA FROM SCHEMAS_2ND),
SUPERSETS_2ND AS
    (SELECT o1.PATH PATH, o1.SCHEMA O1SCHEMA, o1.OSCHEMA O1OSCHEMA, o2.SCHEMA O2SCHEMA, o2.OSCHEMA O2OSCHEMA  FROM OSCHEMAS_2ND o1 CROSS JOIN OSCHEMAS_2ND o2
        WHERE o1.OSCHEMA LIKE CONCAT(o2.OSCHEMA, '%') AND o1.OSCHEMA != o2.OSCHEMA)

SELECT COLLECT_LIST(CONCAT(PATH, "|")) PATH, O1OSCHEMA SCHEMA FROM SUPERSETS_2ND s GROUP BY O1OSCHEMA
