//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


DfFieldTypeT = {
'DfString' : 0,
'DfInt32' : 1,
'DfUInt32' : 2,
'DfInt64' : 3,
'DfUInt64' : 4,
'DfFloat32' : 5,
'DfFloat64' : 6,
'DfBoolean' : 7,
'DfTimespec' : 8,
'DfBlob' : 9,
'DfNull' : 10
};
DfFormatTypeT = {
'DfTypeUnknown' : 0,
'DfTypeJSON' : 1,
'DfTypeRandom' : 2,
'DfTypeCSV' : 3
};
DfFieldTypeTStr = {0 : 'DfString',
1 : 'DfInt32',
2 : 'DfUInt32',
3 : 'DfInt64',
4 : 'DfUInt64',
5 : 'DfFloat32',
6 : 'DfFloat64',
7 : 'DfBoolean',
8 : 'DfTimespec',
9 : 'DfBlob',
10 : 'DfNull'
};
DfFormatTypeTStr = {0 : 'DfTypeUnknown',
1 : 'DfTypeJSON',
2 : 'DfTypeRandom',
3 : 'DfTypeCSV'
};
