//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApisT = {
'XcalarApiUnknown' : 0,
'XcalarApiBulkLoad' : 1,
'XcalarApiCountUnique' : 2,
'XcalarApiShutdown' : 3,
'XcalarApiLargestHitCount' : 4,
'XcalarApiGetStat' : 5,
'XcalarApiResetStat' : 6,
'XcalarApiListTables' : 7,
'XcalarApiShutdownLocal' : 8,
'XcalarApiMakeResultSet' : 9,
'XcalarApiResultSetNext' : 10,
'XcalarApiJoin' : 11,
'XcalarApiFilter' : 12,
'XcalarApiGroupBy' : 13,
'XcalarApiGetDataDict' : 14,
'XcalarApiEditColumn' : 15,
'XcalarApiResultSetAbsolute' : 16,
'XcalarApiFreeResultSet' : 17,
'XcalarApiDeleteTable' : 18,
'XcalarApiGetTableRefCount' : 19
};
XcalarApisTStr = {0 : 'XcalarApiUnknown',
1 : 'XcalarApiBulkLoad',
2 : 'XcalarApiCountUnique',
3 : 'XcalarApiShutdown',
4 : 'XcalarApiLargestHitCount',
5 : 'XcalarApiGetStat',
6 : 'XcalarApiResetStat',
7 : 'XcalarApiListTables',
8 : 'XcalarApiShutdownLocal',
9 : 'XcalarApiMakeResultSet',
10 : 'XcalarApiResultSetNext',
11 : 'XcalarApiJoin',
12 : 'XcalarApiFilter',
13 : 'XcalarApiGroupBy',
14 : 'XcalarApiGetDataDict',
15 : 'XcalarApiEditColumn',
16 : 'XcalarApiResultSetAbsolute',
17 : 'XcalarApiFreeResultSet',
18 : 'XcalarApiDeleteTable',
19 : 'XcalarApiGetTableRefCount'
};
