//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApisT = {
'XcalarApiUnknown' : 0,
'XcalarApiBulkLoad' : 1,
'XcalarApiCountUnique' : 2,
'XcalarApiShutdown' : 3,
'XcalarApiLargestHitCount' : 4,
'XcalarApiGetStat' : 5,
'XcalarApiListTables' : 6,
'XcalarApiShutdownLocal' : 7,
'XcalarApiMakeResultSet' : 8,
'XcalarApiResultSetNext' : 9,
'XcalarApiJoin' : 10,
'XcalarApiFilter' : 11,
'XcalarApiGroupBy' : 12,
'XcalarApiGetDataDict' : 13,
'XcalarApiEditColumn' : 14,
'XcalarApiIsCmdComplete' : 15,
'XcalarApiResultSetAbsolute' : 16
};
XcalarApisTStr = {0 : 'XcalarApiUnknown',
1 : 'XcalarApiBulkLoad',
2 : 'XcalarApiCountUnique',
3 : 'XcalarApiShutdown',
4 : 'XcalarApiLargestHitCount',
5 : 'XcalarApiGetStat',
6 : 'XcalarApiListTables',
7 : 'XcalarApiShutdownLocal',
8 : 'XcalarApiMakeResultSet',
9 : 'XcalarApiResultSetNext',
10 : 'XcalarApiJoin',
11 : 'XcalarApiFilter',
12 : 'XcalarApiGroupBy',
13 : 'XcalarApiGetDataDict',
14 : 'XcalarApiEditColumn',
15 : 'XcalarApiIsCmdComplete',
16 : 'XcalarApiResultSetAbsolute'
};
