//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiException = function(args) {
  this.status = null;
  if (args) {
    if (args.status !== undefined) {
      this.status = args.status;
    }
  }
};
Thrift.inherits(XcalarApiException, Thrift.TException);
XcalarApiException.prototype.name = 'XcalarApiException';
XcalarApiException.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.status = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiException.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiException');
  if (this.status !== null && this.status !== undefined) {
    output.writeFieldBegin('status', Thrift.Type.I32, 1);
    output.writeI32(this.status);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

DfFieldAttrT = function(args) {
  this.name = null;
  this.type = null;
  this.len = null;
  if (args) {
    if (args.name !== undefined) {
      this.name = args.name;
    }
    if (args.type !== undefined) {
      this.type = args.type;
    }
    if (args.len !== undefined) {
      this.len = args.len;
    }
  }
};
DfFieldAttrT.prototype = {};
DfFieldAttrT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.name = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.type = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.len = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DfFieldAttrT.prototype.write = function(output) {
  output.writeStructBegin('DfFieldAttrT');
  if (this.name !== null && this.name !== undefined) {
    output.writeFieldBegin('name', Thrift.Type.STRING, 1);
    output.writeString(this.name);
    output.writeFieldEnd();
  }
  if (this.type !== null && this.type !== undefined) {
    output.writeFieldBegin('type', Thrift.Type.I32, 2);
    output.writeI32(this.type);
    output.writeFieldEnd();
  }
  if (this.len !== null && this.len !== undefined) {
    output.writeFieldBegin('len', Thrift.Type.I64, 3);
    output.writeI64(this.len);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

OperatorsMetaT = function(args) {
  this.fieldAttr = null;
  this.fieldAttrValid = null;
  this.entryType = null;
  this.valuesType = null;
  if (args) {
    if (args.fieldAttr !== undefined) {
      this.fieldAttr = args.fieldAttr;
    }
    if (args.fieldAttrValid !== undefined) {
      this.fieldAttrValid = args.fieldAttrValid;
    }
    if (args.entryType !== undefined) {
      this.entryType = args.entryType;
    }
    if (args.valuesType !== undefined) {
      this.valuesType = args.valuesType;
    }
  }
};
OperatorsMetaT.prototype = {};
OperatorsMetaT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.fieldAttr = new DfFieldAttrT();
        this.fieldAttr.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.BOOL) {
        this.fieldAttrValid = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BYTE) {
        this.entryType = input.readByte().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.valuesType = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

OperatorsMetaT.prototype.write = function(output) {
  output.writeStructBegin('OperatorsMetaT');
  if (this.fieldAttr !== null && this.fieldAttr !== undefined) {
    output.writeFieldBegin('fieldAttr', Thrift.Type.STRUCT, 1);
    this.fieldAttr.write(output);
    output.writeFieldEnd();
  }
  if (this.fieldAttrValid !== null && this.fieldAttrValid !== undefined) {
    output.writeFieldBegin('fieldAttrValid', Thrift.Type.BOOL, 2);
    output.writeBool(this.fieldAttrValid);
    output.writeFieldEnd();
  }
  if (this.entryType !== null && this.entryType !== undefined) {
    output.writeFieldBegin('entryType', Thrift.Type.BYTE, 3);
    output.writeByte(this.entryType);
    output.writeFieldEnd();
  }
  if (this.valuesType !== null && this.valuesType !== undefined) {
    output.writeFieldBegin('valuesType', Thrift.Type.I32, 4);
    output.writeI32(this.valuesType);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

KeyValuePairT = function(args) {
  this.key = null;
  this.value = null;
  if (args) {
    if (args.key !== undefined) {
      this.key = args.key;
    }
    if (args.value !== undefined) {
      this.value = args.value;
    }
  }
};
KeyValuePairT.prototype = {};
KeyValuePairT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.key = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.value = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

KeyValuePairT.prototype.write = function(output) {
  output.writeStructBegin('KeyValuePairT');
  if (this.key !== null && this.key !== undefined) {
    output.writeFieldBegin('key', Thrift.Type.I64, 1);
    output.writeI64(this.key);
    output.writeFieldEnd();
  }
  if (this.value !== null && this.value !== undefined) {
    output.writeFieldBegin('value', Thrift.Type.STRING, 2);
    output.writeString(this.value);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiTableT = function(args) {
  this.tableName = null;
  this.handle = null;
  this.backingDatasetId = null;
  if (args) {
    if (args.tableName !== undefined) {
      this.tableName = args.tableName;
    }
    if (args.handle !== undefined) {
      this.handle = args.handle;
    }
    if (args.backingDatasetId !== undefined) {
      this.backingDatasetId = args.backingDatasetId;
    }
  }
};
XcalarApiTableT.prototype = {};
XcalarApiTableT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.tableName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.handle = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.backingDatasetId = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiTableT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiTableT');
  if (this.tableName !== null && this.tableName !== undefined) {
    output.writeFieldBegin('tableName', Thrift.Type.STRING, 1);
    output.writeString(this.tableName);
    output.writeFieldEnd();
  }
  if (this.handle !== null && this.handle !== undefined) {
    output.writeFieldBegin('handle', Thrift.Type.I64, 2);
    output.writeI64(this.handle);
    output.writeFieldEnd();
  }
  if (this.backingDatasetId !== null && this.backingDatasetId !== undefined) {
    output.writeFieldBegin('backingDatasetId', Thrift.Type.I64, 3);
    output.writeI64(this.backingDatasetId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiBulkLoadInputT = function(args) {
  this.loadFromPath = null;
  this.path = null;
  this.maxSize = null;
  this.dfType = null;
  this.keyName = null;
  this.srcTable = null;
  this.dstTable = null;
  if (args) {
    if (args.loadFromPath !== undefined) {
      this.loadFromPath = args.loadFromPath;
    }
    if (args.path !== undefined) {
      this.path = args.path;
    }
    if (args.maxSize !== undefined) {
      this.maxSize = args.maxSize;
    }
    if (args.dfType !== undefined) {
      this.dfType = args.dfType;
    }
    if (args.keyName !== undefined) {
      this.keyName = args.keyName;
    }
    if (args.srcTable !== undefined) {
      this.srcTable = args.srcTable;
    }
    if (args.dstTable !== undefined) {
      this.dstTable = args.dstTable;
    }
  }
};
XcalarApiBulkLoadInputT.prototype = {};
XcalarApiBulkLoadInputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.loadFromPath = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.path = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.maxSize = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.dfType = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRING) {
        this.keyName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.STRUCT) {
        this.srcTable = new XcalarApiTableT();
        this.srcTable.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRUCT) {
        this.dstTable = new XcalarApiTableT();
        this.dstTable.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiBulkLoadInputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiBulkLoadInputT');
  if (this.loadFromPath !== null && this.loadFromPath !== undefined) {
    output.writeFieldBegin('loadFromPath', Thrift.Type.BOOL, 1);
    output.writeBool(this.loadFromPath);
    output.writeFieldEnd();
  }
  if (this.path !== null && this.path !== undefined) {
    output.writeFieldBegin('path', Thrift.Type.STRING, 2);
    output.writeString(this.path);
    output.writeFieldEnd();
  }
  if (this.maxSize !== null && this.maxSize !== undefined) {
    output.writeFieldBegin('maxSize', Thrift.Type.I64, 3);
    output.writeI64(this.maxSize);
    output.writeFieldEnd();
  }
  if (this.dfType !== null && this.dfType !== undefined) {
    output.writeFieldBegin('dfType', Thrift.Type.I32, 4);
    output.writeI32(this.dfType);
    output.writeFieldEnd();
  }
  if (this.keyName !== null && this.keyName !== undefined) {
    output.writeFieldBegin('keyName', Thrift.Type.STRING, 5);
    output.writeString(this.keyName);
    output.writeFieldEnd();
  }
  if (this.srcTable !== null && this.srcTable !== undefined) {
    output.writeFieldBegin('srcTable', Thrift.Type.STRUCT, 6);
    this.srcTable.write(output);
    output.writeFieldEnd();
  }
  if (this.dstTable !== null && this.dstTable !== undefined) {
    output.writeFieldBegin('dstTable', Thrift.Type.STRUCT, 7);
    this.dstTable.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiStatInputT = function(args) {
  this.nodeId = null;
  if (args) {
    if (args.nodeId !== undefined) {
      this.nodeId = args.nodeId;
    }
  }
};
XcalarApiStatInputT.prototype = {};
XcalarApiStatInputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.nodeId = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiStatInputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiStatInputT');
  if (this.nodeId !== null && this.nodeId !== undefined) {
    output.writeFieldBegin('nodeId', Thrift.Type.I64, 1);
    output.writeI64(this.nodeId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiFilterInputT = function(args) {
  this.table = null;
  this.filterTable = null;
  this.filterOp = null;
  this.compValue = null;
  if (args) {
    if (args.table !== undefined) {
      this.table = args.table;
    }
    if (args.filterTable !== undefined) {
      this.filterTable = args.filterTable;
    }
    if (args.filterOp !== undefined) {
      this.filterOp = args.filterOp;
    }
    if (args.compValue !== undefined) {
      this.compValue = args.compValue;
    }
  }
};
XcalarApiFilterInputT.prototype = {};
XcalarApiFilterInputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.table = new XcalarApiTableT();
        this.table.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.filterTable = new XcalarApiTableT();
        this.filterTable.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.filterOp = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I64) {
        this.compValue = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiFilterInputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiFilterInputT');
  if (this.table !== null && this.table !== undefined) {
    output.writeFieldBegin('table', Thrift.Type.STRUCT, 1);
    this.table.write(output);
    output.writeFieldEnd();
  }
  if (this.filterTable !== null && this.filterTable !== undefined) {
    output.writeFieldBegin('filterTable', Thrift.Type.STRUCT, 2);
    this.filterTable.write(output);
    output.writeFieldEnd();
  }
  if (this.filterOp !== null && this.filterOp !== undefined) {
    output.writeFieldBegin('filterOp', Thrift.Type.I32, 3);
    output.writeI32(this.filterOp);
    output.writeFieldEnd();
  }
  if (this.compValue !== null && this.compValue !== undefined) {
    output.writeFieldBegin('compValue', Thrift.Type.I64, 4);
    output.writeI64(this.compValue);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiGroupByInputT = function(args) {
  this.table = null;
  this.groupByTable = null;
  this.groupByOp = null;
  if (args) {
    if (args.table !== undefined) {
      this.table = args.table;
    }
    if (args.groupByTable !== undefined) {
      this.groupByTable = args.groupByTable;
    }
    if (args.groupByOp !== undefined) {
      this.groupByOp = args.groupByOp;
    }
  }
};
XcalarApiGroupByInputT.prototype = {};
XcalarApiGroupByInputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.table = new XcalarApiTableT();
        this.table.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.groupByTable = new XcalarApiTableT();
        this.groupByTable.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.groupByOp = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiGroupByInputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiGroupByInputT');
  if (this.table !== null && this.table !== undefined) {
    output.writeFieldBegin('table', Thrift.Type.STRUCT, 1);
    this.table.write(output);
    output.writeFieldEnd();
  }
  if (this.groupByTable !== null && this.groupByTable !== undefined) {
    output.writeFieldBegin('groupByTable', Thrift.Type.STRUCT, 2);
    this.groupByTable.write(output);
    output.writeFieldEnd();
  }
  if (this.groupByOp !== null && this.groupByOp !== undefined) {
    output.writeFieldBegin('groupByOp', Thrift.Type.I32, 3);
    output.writeI32(this.groupByOp);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiEditColInputT = function(args) {
  this.table = null;
  this.currFieldName = null;
  this.newFieldName = null;
  this.newFieldType = null;
  if (args) {
    if (args.table !== undefined) {
      this.table = args.table;
    }
    if (args.currFieldName !== undefined) {
      this.currFieldName = args.currFieldName;
    }
    if (args.newFieldName !== undefined) {
      this.newFieldName = args.newFieldName;
    }
    if (args.newFieldType !== undefined) {
      this.newFieldType = args.newFieldType;
    }
  }
};
XcalarApiEditColInputT.prototype = {};
XcalarApiEditColInputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.table = new XcalarApiTableT();
        this.table.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.currFieldName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.newFieldName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.newFieldType = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiEditColInputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiEditColInputT');
  if (this.table !== null && this.table !== undefined) {
    output.writeFieldBegin('table', Thrift.Type.STRUCT, 1);
    this.table.write(output);
    output.writeFieldEnd();
  }
  if (this.currFieldName !== null && this.currFieldName !== undefined) {
    output.writeFieldBegin('currFieldName', Thrift.Type.STRING, 2);
    output.writeString(this.currFieldName);
    output.writeFieldEnd();
  }
  if (this.newFieldName !== null && this.newFieldName !== undefined) {
    output.writeFieldBegin('newFieldName', Thrift.Type.STRING, 3);
    output.writeString(this.newFieldName);
    output.writeFieldEnd();
  }
  if (this.newFieldType !== null && this.newFieldType !== undefined) {
    output.writeFieldBegin('newFieldType', Thrift.Type.I32, 4);
    output.writeI32(this.newFieldType);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiResultSetNextInputT = function(args) {
  this.resultSetId = null;
  this.numRecords = null;
  if (args) {
    if (args.resultSetId !== undefined) {
      this.resultSetId = args.resultSetId;
    }
    if (args.numRecords !== undefined) {
      this.numRecords = args.numRecords;
    }
  }
};
XcalarApiResultSetNextInputT.prototype = {};
XcalarApiResultSetNextInputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.resultSetId = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.numRecords = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiResultSetNextInputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiResultSetNextInputT');
  if (this.resultSetId !== null && this.resultSetId !== undefined) {
    output.writeFieldBegin('resultSetId', Thrift.Type.I64, 1);
    output.writeI64(this.resultSetId);
    output.writeFieldEnd();
  }
  if (this.numRecords !== null && this.numRecords !== undefined) {
    output.writeFieldBegin('numRecords', Thrift.Type.I64, 2);
    output.writeI64(this.numRecords);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiFreeResultSetInputT = function(args) {
  this.resultSetId = null;
  if (args) {
    if (args.resultSetId !== undefined) {
      this.resultSetId = args.resultSetId;
    }
  }
};
XcalarApiFreeResultSetInputT.prototype = {};
XcalarApiFreeResultSetInputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.resultSetId = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiFreeResultSetInputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiFreeResultSetInputT');
  if (this.resultSetId !== null && this.resultSetId !== undefined) {
    output.writeFieldBegin('resultSetId', Thrift.Type.I64, 1);
    output.writeI64(this.resultSetId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiStatT = function(args) {
  this.threadName = null;
  this.statName = null;
  this.statValue = null;
  this.statType = null;
  this.statLife = null;
  if (args) {
    if (args.threadName !== undefined) {
      this.threadName = args.threadName;
    }
    if (args.statName !== undefined) {
      this.statName = args.statName;
    }
    if (args.statValue !== undefined) {
      this.statValue = args.statValue;
    }
    if (args.statType !== undefined) {
      this.statType = args.statType;
    }
    if (args.statLife !== undefined) {
      this.statLife = args.statLife;
    }
  }
};
XcalarApiStatT.prototype = {};
XcalarApiStatT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.threadName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.statName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.statValue = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.statType = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I32) {
        this.statLife = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiStatT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiStatT');
  if (this.threadName !== null && this.threadName !== undefined) {
    output.writeFieldBegin('threadName', Thrift.Type.STRING, 1);
    output.writeString(this.threadName);
    output.writeFieldEnd();
  }
  if (this.statName !== null && this.statName !== undefined) {
    output.writeFieldBegin('statName', Thrift.Type.STRING, 2);
    output.writeString(this.statName);
    output.writeFieldEnd();
  }
  if (this.statValue !== null && this.statValue !== undefined) {
    output.writeFieldBegin('statValue', Thrift.Type.I64, 3);
    output.writeI64(this.statValue);
    output.writeFieldEnd();
  }
  if (this.statType !== null && this.statType !== undefined) {
    output.writeFieldBegin('statType', Thrift.Type.I32, 4);
    output.writeI32(this.statType);
    output.writeFieldEnd();
  }
  if (this.statLife !== null && this.statLife !== undefined) {
    output.writeFieldBegin('statLife', Thrift.Type.I32, 5);
    output.writeI32(this.statLife);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiJoinInputT = function(args) {
  this.leftTable = null;
  this.rightTable = null;
  this.joinTable = null;
  this.joinType = null;
  if (args) {
    if (args.leftTable !== undefined) {
      this.leftTable = args.leftTable;
    }
    if (args.rightTable !== undefined) {
      this.rightTable = args.rightTable;
    }
    if (args.joinTable !== undefined) {
      this.joinTable = args.joinTable;
    }
    if (args.joinType !== undefined) {
      this.joinType = args.joinType;
    }
  }
};
XcalarApiJoinInputT.prototype = {};
XcalarApiJoinInputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.leftTable = new XcalarApiTableT();
        this.leftTable.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.rightTable = new XcalarApiTableT();
        this.rightTable.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.joinTable = new XcalarApiTableT();
        this.joinTable.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.joinType = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiJoinInputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiJoinInputT');
  if (this.leftTable !== null && this.leftTable !== undefined) {
    output.writeFieldBegin('leftTable', Thrift.Type.STRUCT, 1);
    this.leftTable.write(output);
    output.writeFieldEnd();
  }
  if (this.rightTable !== null && this.rightTable !== undefined) {
    output.writeFieldBegin('rightTable', Thrift.Type.STRUCT, 2);
    this.rightTable.write(output);
    output.writeFieldEnd();
  }
  if (this.joinTable !== null && this.joinTable !== undefined) {
    output.writeFieldBegin('joinTable', Thrift.Type.STRUCT, 3);
    this.joinTable.write(output);
    output.writeFieldEnd();
  }
  if (this.joinType !== null && this.joinType !== undefined) {
    output.writeFieldBegin('joinType', Thrift.Type.I32, 4);
    output.writeI32(this.joinType);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiGetDataDictInputT = function(args) {
  this.table = null;
  this.formatType = null;
  if (args) {
    if (args.table !== undefined) {
      this.table = args.table;
    }
    if (args.formatType !== undefined) {
      this.formatType = args.formatType;
    }
  }
};
XcalarApiGetDataDictInputT.prototype = {};
XcalarApiGetDataDictInputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.table = new XcalarApiTableT();
        this.table.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.formatType = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiGetDataDictInputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiGetDataDictInputT');
  if (this.table !== null && this.table !== undefined) {
    output.writeFieldBegin('table', Thrift.Type.STRUCT, 1);
    this.table.write(output);
    output.writeFieldEnd();
  }
  if (this.formatType !== null && this.formatType !== undefined) {
    output.writeFieldBegin('formatType', Thrift.Type.I32, 2);
    output.writeI32(this.formatType);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiResultSetAbsoluteInputT = function(args) {
  this.resultSetId = null;
  this.position = null;
  if (args) {
    if (args.resultSetId !== undefined) {
      this.resultSetId = args.resultSetId;
    }
    if (args.position !== undefined) {
      this.position = args.position;
    }
  }
};
XcalarApiResultSetAbsoluteInputT.prototype = {};
XcalarApiResultSetAbsoluteInputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.resultSetId = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.position = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiResultSetAbsoluteInputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiResultSetAbsoluteInputT');
  if (this.resultSetId !== null && this.resultSetId !== undefined) {
    output.writeFieldBegin('resultSetId', Thrift.Type.I64, 1);
    output.writeI64(this.resultSetId);
    output.writeFieldEnd();
  }
  if (this.position !== null && this.position !== undefined) {
    output.writeFieldBegin('position', Thrift.Type.I64, 2);
    output.writeI64(this.position);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

DsCsvDataDictionaryT = function(args) {
  this.numFields = null;
  this.fields = null;
  if (args) {
    if (args.numFields !== undefined) {
      this.numFields = args.numFields;
    }
    if (args.fields !== undefined) {
      this.fields = args.fields;
    }
  }
};
DsCsvDataDictionaryT.prototype = {};
DsCsvDataDictionaryT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I64) {
        this.numFields = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.LIST) {
        var _size0 = 0;
        var _rtmp34;
        this.fields = [];
        var _etype3 = 0;
        _rtmp34 = input.readListBegin();
        _etype3 = _rtmp34.etype;
        _size0 = _rtmp34.size;
        for (var _i5 = 0; _i5 < _size0; ++_i5)
        {
          var elem6 = null;
          elem6 = new DfFieldAttrT();
          elem6.read(input);
          this.fields.push(elem6);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DsCsvDataDictionaryT.prototype.write = function(output) {
  output.writeStructBegin('DsCsvDataDictionaryT');
  if (this.numFields !== null && this.numFields !== undefined) {
    output.writeFieldBegin('numFields', Thrift.Type.I64, 1);
    output.writeI64(this.numFields);
    output.writeFieldEnd();
  }
  if (this.fields !== null && this.fields !== undefined) {
    output.writeFieldBegin('fields', Thrift.Type.LIST, 2);
    output.writeListBegin(Thrift.Type.STRUCT, this.fields.length);
    for (var iter7 in this.fields)
    {
      if (this.fields.hasOwnProperty(iter7))
      {
        iter7 = this.fields[iter7];
        iter7.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

DsDataDictionaryT = function(args) {
  this.formatType = null;
  this.dictionarySize = null;
  this.csvDataDictionary = null;
  if (args) {
    if (args.formatType !== undefined) {
      this.formatType = args.formatType;
    }
    if (args.dictionarySize !== undefined) {
      this.dictionarySize = args.dictionarySize;
    }
    if (args.csvDataDictionary !== undefined) {
      this.csvDataDictionary = args.csvDataDictionary;
    }
  }
};
DsDataDictionaryT.prototype = {};
DsDataDictionaryT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.formatType = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.dictionarySize = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.csvDataDictionary = new DsCsvDataDictionaryT();
        this.csvDataDictionary.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DsDataDictionaryT.prototype.write = function(output) {
  output.writeStructBegin('DsDataDictionaryT');
  if (this.formatType !== null && this.formatType !== undefined) {
    output.writeFieldBegin('formatType', Thrift.Type.I32, 1);
    output.writeI32(this.formatType);
    output.writeFieldEnd();
  }
  if (this.dictionarySize !== null && this.dictionarySize !== undefined) {
    output.writeFieldBegin('dictionarySize', Thrift.Type.I64, 2);
    output.writeI64(this.dictionarySize);
    output.writeFieldEnd();
  }
  if (this.csvDataDictionary !== null && this.csvDataDictionary !== undefined) {
    output.writeFieldBegin('csvDataDictionary', Thrift.Type.STRUCT, 3);
    this.csvDataDictionary.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiGetDataDictOutputT = function(args) {
  this.status = null;
  this.dataDictionary = null;
  if (args) {
    if (args.status !== undefined) {
      this.status = args.status;
    }
    if (args.dataDictionary !== undefined) {
      this.dataDictionary = args.dataDictionary;
    }
  }
};
XcalarApiGetDataDictOutputT.prototype = {};
XcalarApiGetDataDictOutputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.status = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.dataDictionary = new DsDataDictionaryT();
        this.dataDictionary.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiGetDataDictOutputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiGetDataDictOutputT');
  if (this.status !== null && this.status !== undefined) {
    output.writeFieldBegin('status', Thrift.Type.I32, 1);
    output.writeI32(this.status);
    output.writeFieldEnd();
  }
  if (this.dataDictionary !== null && this.dataDictionary !== undefined) {
    output.writeFieldBegin('dataDictionary', Thrift.Type.STRUCT, 2);
    this.dataDictionary.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiGetStatOutputT = function(args) {
  this.status = null;
  this.numStats = null;
  this.stats = null;
  if (args) {
    if (args.status !== undefined) {
      this.status = args.status;
    }
    if (args.numStats !== undefined) {
      this.numStats = args.numStats;
    }
    if (args.stats !== undefined) {
      this.stats = args.stats;
    }
  }
};
XcalarApiGetStatOutputT.prototype = {};
XcalarApiGetStatOutputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.status = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.numStats = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.LIST) {
        var _size8 = 0;
        var _rtmp312;
        this.stats = [];
        var _etype11 = 0;
        _rtmp312 = input.readListBegin();
        _etype11 = _rtmp312.etype;
        _size8 = _rtmp312.size;
        for (var _i13 = 0; _i13 < _size8; ++_i13)
        {
          var elem14 = null;
          elem14 = new XcalarApiStatT();
          elem14.read(input);
          this.stats.push(elem14);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiGetStatOutputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiGetStatOutputT');
  if (this.status !== null && this.status !== undefined) {
    output.writeFieldBegin('status', Thrift.Type.I32, 1);
    output.writeI32(this.status);
    output.writeFieldEnd();
  }
  if (this.numStats !== null && this.numStats !== undefined) {
    output.writeFieldBegin('numStats', Thrift.Type.I64, 2);
    output.writeI64(this.numStats);
    output.writeFieldEnd();
  }
  if (this.stats !== null && this.stats !== undefined) {
    output.writeFieldBegin('stats', Thrift.Type.LIST, 3);
    output.writeListBegin(Thrift.Type.STRUCT, this.stats.length);
    for (var iter15 in this.stats)
    {
      if (this.stats.hasOwnProperty(iter15))
      {
        iter15 = this.stats[iter15];
        iter15.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiCountOutputT = function(args) {
  this.status = null;
  this.numCounts = null;
  this.counts = null;
  if (args) {
    if (args.status !== undefined) {
      this.status = args.status;
    }
    if (args.numCounts !== undefined) {
      this.numCounts = args.numCounts;
    }
    if (args.counts !== undefined) {
      this.counts = args.counts;
    }
  }
};
XcalarApiCountOutputT.prototype = {};
XcalarApiCountOutputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.status = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.numCounts = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.LIST) {
        var _size16 = 0;
        var _rtmp320;
        this.counts = [];
        var _etype19 = 0;
        _rtmp320 = input.readListBegin();
        _etype19 = _rtmp320.etype;
        _size16 = _rtmp320.size;
        for (var _i21 = 0; _i21 < _size16; ++_i21)
        {
          var elem22 = null;
          elem22 = input.readI64().value;
          this.counts.push(elem22);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiCountOutputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiCountOutputT');
  if (this.status !== null && this.status !== undefined) {
    output.writeFieldBegin('status', Thrift.Type.I32, 1);
    output.writeI32(this.status);
    output.writeFieldEnd();
  }
  if (this.numCounts !== null && this.numCounts !== undefined) {
    output.writeFieldBegin('numCounts', Thrift.Type.I64, 2);
    output.writeI64(this.numCounts);
    output.writeFieldEnd();
  }
  if (this.counts !== null && this.counts !== undefined) {
    output.writeFieldBegin('counts', Thrift.Type.LIST, 3);
    output.writeListBegin(Thrift.Type.I64, this.counts.length);
    for (var iter23 in this.counts)
    {
      if (this.counts.hasOwnProperty(iter23))
      {
        iter23 = this.counts[iter23];
        output.writeI64(iter23);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiMakeResultSetOutputT = function(args) {
  this.status = null;
  this.resultSetId = null;
  this.numEntries = null;
  if (args) {
    if (args.status !== undefined) {
      this.status = args.status;
    }
    if (args.resultSetId !== undefined) {
      this.resultSetId = args.resultSetId;
    }
    if (args.numEntries !== undefined) {
      this.numEntries = args.numEntries;
    }
  }
};
XcalarApiMakeResultSetOutputT.prototype = {};
XcalarApiMakeResultSetOutputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.status = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.resultSetId = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I64) {
        this.numEntries = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiMakeResultSetOutputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiMakeResultSetOutputT');
  if (this.status !== null && this.status !== undefined) {
    output.writeFieldBegin('status', Thrift.Type.I32, 1);
    output.writeI32(this.status);
    output.writeFieldEnd();
  }
  if (this.resultSetId !== null && this.resultSetId !== undefined) {
    output.writeFieldBegin('resultSetId', Thrift.Type.I64, 2);
    output.writeI64(this.resultSetId);
    output.writeFieldEnd();
  }
  if (this.numEntries !== null && this.numEntries !== undefined) {
    output.writeFieldBegin('numEntries', Thrift.Type.I64, 3);
    output.writeI64(this.numEntries);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiResultSetNextOutputT = function(args) {
  this.status = null;
  this.meta = null;
  this.numRecords = null;
  this.records = null;
  if (args) {
    if (args.status !== undefined) {
      this.status = args.status;
    }
    if (args.meta !== undefined) {
      this.meta = args.meta;
    }
    if (args.numRecords !== undefined) {
      this.numRecords = args.numRecords;
    }
    if (args.records !== undefined) {
      this.records = args.records;
    }
  }
};
XcalarApiResultSetNextOutputT.prototype = {};
XcalarApiResultSetNextOutputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.status = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.meta = new OperatorsMetaT();
        this.meta.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.numRecords = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.LIST) {
        var _size24 = 0;
        var _rtmp328;
        this.records = [];
        var _etype27 = 0;
        _rtmp328 = input.readListBegin();
        _etype27 = _rtmp328.etype;
        _size24 = _rtmp328.size;
        for (var _i29 = 0; _i29 < _size24; ++_i29)
        {
          var elem30 = null;
          elem30 = new KeyValuePairT();
          elem30.read(input);
          this.records.push(elem30);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiResultSetNextOutputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiResultSetNextOutputT');
  if (this.status !== null && this.status !== undefined) {
    output.writeFieldBegin('status', Thrift.Type.I32, 1);
    output.writeI32(this.status);
    output.writeFieldEnd();
  }
  if (this.meta !== null && this.meta !== undefined) {
    output.writeFieldBegin('meta', Thrift.Type.STRUCT, 2);
    this.meta.write(output);
    output.writeFieldEnd();
  }
  if (this.numRecords !== null && this.numRecords !== undefined) {
    output.writeFieldBegin('numRecords', Thrift.Type.I32, 3);
    output.writeI32(this.numRecords);
    output.writeFieldEnd();
  }
  if (this.records !== null && this.records !== undefined) {
    output.writeFieldBegin('records', Thrift.Type.LIST, 4);
    output.writeListBegin(Thrift.Type.STRUCT, this.records.length);
    for (var iter31 in this.records)
    {
      if (this.records.hasOwnProperty(iter31))
      {
        iter31 = this.records[iter31];
        iter31.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiListTablesOutputT = function(args) {
  this.numTables = null;
  this.tables = null;
  if (args) {
    if (args.numTables !== undefined) {
      this.numTables = args.numTables;
    }
    if (args.tables !== undefined) {
      this.tables = args.tables;
    }
  }
};
XcalarApiListTablesOutputT.prototype = {};
XcalarApiListTablesOutputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.numTables = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.LIST) {
        var _size32 = 0;
        var _rtmp336;
        this.tables = [];
        var _etype35 = 0;
        _rtmp336 = input.readListBegin();
        _etype35 = _rtmp336.etype;
        _size32 = _rtmp336.size;
        for (var _i37 = 0; _i37 < _size32; ++_i37)
        {
          var elem38 = null;
          elem38 = new XcalarApiTableT();
          elem38.read(input);
          this.tables.push(elem38);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiListTablesOutputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiListTablesOutputT');
  if (this.numTables !== null && this.numTables !== undefined) {
    output.writeFieldBegin('numTables', Thrift.Type.I32, 1);
    output.writeI32(this.numTables);
    output.writeFieldEnd();
  }
  if (this.tables !== null && this.tables !== undefined) {
    output.writeFieldBegin('tables', Thrift.Type.LIST, 2);
    output.writeListBegin(Thrift.Type.STRUCT, this.tables.length);
    for (var iter39 in this.tables)
    {
      if (this.tables.hasOwnProperty(iter39))
      {
        iter39 = this.tables[iter39];
        iter39.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiDeleteTableStatusT = function(args) {
  this.table = null;
  this.status = null;
  if (args) {
    if (args.table !== undefined) {
      this.table = args.table;
    }
    if (args.status !== undefined) {
      this.status = args.status;
    }
  }
};
XcalarApiDeleteTableStatusT.prototype = {};
XcalarApiDeleteTableStatusT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.table = new XcalarApiTableT();
        this.table.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.status = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiDeleteTableStatusT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiDeleteTableStatusT');
  if (this.table !== null && this.table !== undefined) {
    output.writeFieldBegin('table', Thrift.Type.STRUCT, 1);
    this.table.write(output);
    output.writeFieldEnd();
  }
  if (this.status !== null && this.status !== undefined) {
    output.writeFieldBegin('status', Thrift.Type.I32, 2);
    output.writeI32(this.status);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiBulkDeleteTablesOutputT = function(args) {
  this.numTables = null;
  this.status = null;
  this.statuses = null;
  if (args) {
    if (args.numTables !== undefined) {
      this.numTables = args.numTables;
    }
    if (args.status !== undefined) {
      this.status = args.status;
    }
    if (args.statuses !== undefined) {
      this.statuses = args.statuses;
    }
  }
};
XcalarApiBulkDeleteTablesOutputT.prototype = {};
XcalarApiBulkDeleteTablesOutputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.numTables = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.status = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.LIST) {
        var _size40 = 0;
        var _rtmp344;
        this.statuses = [];
        var _etype43 = 0;
        _rtmp344 = input.readListBegin();
        _etype43 = _rtmp344.etype;
        _size40 = _rtmp344.size;
        for (var _i45 = 0; _i45 < _size40; ++_i45)
        {
          var elem46 = null;
          elem46 = new XcalarApiDeleteTableStatusT();
          elem46.read(input);
          this.statuses.push(elem46);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiBulkDeleteTablesOutputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiBulkDeleteTablesOutputT');
  if (this.numTables !== null && this.numTables !== undefined) {
    output.writeFieldBegin('numTables', Thrift.Type.I32, 1);
    output.writeI32(this.numTables);
    output.writeFieldEnd();
  }
  if (this.status !== null && this.status !== undefined) {
    output.writeFieldBegin('status', Thrift.Type.I32, 2);
    output.writeI32(this.status);
    output.writeFieldEnd();
  }
  if (this.statuses !== null && this.statuses !== undefined) {
    output.writeFieldBegin('statuses', Thrift.Type.LIST, 3);
    output.writeListBegin(Thrift.Type.STRUCT, this.statuses.length);
    for (var iter47 in this.statuses)
    {
      if (this.statuses.hasOwnProperty(iter47))
      {
        iter47 = this.statuses[iter47];
        iter47.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiNewTableOutputT = function(args) {
  this.status = null;
  this.tableName = null;
  if (args) {
    if (args.status !== undefined) {
      this.status = args.status;
    }
    if (args.tableName !== undefined) {
      this.tableName = args.tableName;
    }
  }
};
XcalarApiNewTableOutputT.prototype = {};
XcalarApiNewTableOutputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.status = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.tableName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiNewTableOutputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiNewTableOutputT');
  if (this.status !== null && this.status !== undefined) {
    output.writeFieldBegin('status', Thrift.Type.I32, 1);
    output.writeI32(this.status);
    output.writeFieldEnd();
  }
  if (this.tableName !== null && this.tableName !== undefined) {
    output.writeFieldBegin('tableName', Thrift.Type.STRING, 2);
    output.writeString(this.tableName);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiGetTableRefCountOutputT = function(args) {
  this.status = null;
  this.refCount = null;
  if (args) {
    if (args.status !== undefined) {
      this.status = args.status;
    }
    if (args.refCount !== undefined) {
      this.refCount = args.refCount;
    }
  }
};
XcalarApiGetTableRefCountOutputT.prototype = {};
XcalarApiGetTableRefCountOutputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.status = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I64) {
        this.refCount = input.readI64().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiGetTableRefCountOutputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiGetTableRefCountOutputT');
  if (this.status !== null && this.status !== undefined) {
    output.writeFieldBegin('status', Thrift.Type.I32, 1);
    output.writeI32(this.status);
    output.writeFieldEnd();
  }
  if (this.refCount !== null && this.refCount !== undefined) {
    output.writeFieldBegin('refCount', Thrift.Type.I64, 2);
    output.writeI64(this.refCount);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiInputT = function(args) {
  this.loadInput = null;
  this.statInput = null;
  this.tableInput = null;
  this.resultSetNextInput = null;
  this.joinInput = null;
  this.filterInput = null;
  this.groupByInput = null;
  this.getDataDictInput = null;
  this.editColInput = null;
  this.resultSetAbsoluteInput = null;
  this.freeResultSetInput = null;
  this.deleteTableInput = null;
  this.getTableRefCountInput = null;
  this.listTablesInput = null;
  this.bulkDeleteTablesInput = null;
  if (args) {
    if (args.loadInput !== undefined) {
      this.loadInput = args.loadInput;
    }
    if (args.statInput !== undefined) {
      this.statInput = args.statInput;
    }
    if (args.tableInput !== undefined) {
      this.tableInput = args.tableInput;
    }
    if (args.resultSetNextInput !== undefined) {
      this.resultSetNextInput = args.resultSetNextInput;
    }
    if (args.joinInput !== undefined) {
      this.joinInput = args.joinInput;
    }
    if (args.filterInput !== undefined) {
      this.filterInput = args.filterInput;
    }
    if (args.groupByInput !== undefined) {
      this.groupByInput = args.groupByInput;
    }
    if (args.getDataDictInput !== undefined) {
      this.getDataDictInput = args.getDataDictInput;
    }
    if (args.editColInput !== undefined) {
      this.editColInput = args.editColInput;
    }
    if (args.resultSetAbsoluteInput !== undefined) {
      this.resultSetAbsoluteInput = args.resultSetAbsoluteInput;
    }
    if (args.freeResultSetInput !== undefined) {
      this.freeResultSetInput = args.freeResultSetInput;
    }
    if (args.deleteTableInput !== undefined) {
      this.deleteTableInput = args.deleteTableInput;
    }
    if (args.getTableRefCountInput !== undefined) {
      this.getTableRefCountInput = args.getTableRefCountInput;
    }
    if (args.listTablesInput !== undefined) {
      this.listTablesInput = args.listTablesInput;
    }
    if (args.bulkDeleteTablesInput !== undefined) {
      this.bulkDeleteTablesInput = args.bulkDeleteTablesInput;
    }
  }
};
XcalarApiInputT.prototype = {};
XcalarApiInputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.loadInput = new XcalarApiBulkLoadInputT();
        this.loadInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.statInput = new XcalarApiStatInputT();
        this.statInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.tableInput = new XcalarApiTableT();
        this.tableInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRUCT) {
        this.resultSetNextInput = new XcalarApiResultSetNextInputT();
        this.resultSetNextInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRUCT) {
        this.joinInput = new XcalarApiJoinInputT();
        this.joinInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.STRUCT) {
        this.filterInput = new XcalarApiFilterInputT();
        this.filterInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRUCT) {
        this.groupByInput = new XcalarApiGroupByInputT();
        this.groupByInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.STRUCT) {
        this.getDataDictInput = new XcalarApiGetDataDictInputT();
        this.getDataDictInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 9:
      if (ftype == Thrift.Type.STRUCT) {
        this.editColInput = new XcalarApiEditColInputT();
        this.editColInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.STRUCT) {
        this.resultSetAbsoluteInput = new XcalarApiResultSetAbsoluteInputT();
        this.resultSetAbsoluteInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 11:
      if (ftype == Thrift.Type.STRUCT) {
        this.freeResultSetInput = new XcalarApiFreeResultSetInputT();
        this.freeResultSetInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 12:
      if (ftype == Thrift.Type.STRUCT) {
        this.deleteTableInput = new XcalarApiTableT();
        this.deleteTableInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 13:
      if (ftype == Thrift.Type.STRUCT) {
        this.getTableRefCountInput = new XcalarApiTableT();
        this.getTableRefCountInput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 14:
      if (ftype == Thrift.Type.STRING) {
        this.listTablesInput = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 15:
      if (ftype == Thrift.Type.STRING) {
        this.bulkDeleteTablesInput = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiInputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiInputT');
  if (this.loadInput !== null && this.loadInput !== undefined) {
    output.writeFieldBegin('loadInput', Thrift.Type.STRUCT, 1);
    this.loadInput.write(output);
    output.writeFieldEnd();
  }
  if (this.statInput !== null && this.statInput !== undefined) {
    output.writeFieldBegin('statInput', Thrift.Type.STRUCT, 2);
    this.statInput.write(output);
    output.writeFieldEnd();
  }
  if (this.tableInput !== null && this.tableInput !== undefined) {
    output.writeFieldBegin('tableInput', Thrift.Type.STRUCT, 3);
    this.tableInput.write(output);
    output.writeFieldEnd();
  }
  if (this.resultSetNextInput !== null && this.resultSetNextInput !== undefined) {
    output.writeFieldBegin('resultSetNextInput', Thrift.Type.STRUCT, 4);
    this.resultSetNextInput.write(output);
    output.writeFieldEnd();
  }
  if (this.joinInput !== null && this.joinInput !== undefined) {
    output.writeFieldBegin('joinInput', Thrift.Type.STRUCT, 5);
    this.joinInput.write(output);
    output.writeFieldEnd();
  }
  if (this.filterInput !== null && this.filterInput !== undefined) {
    output.writeFieldBegin('filterInput', Thrift.Type.STRUCT, 6);
    this.filterInput.write(output);
    output.writeFieldEnd();
  }
  if (this.groupByInput !== null && this.groupByInput !== undefined) {
    output.writeFieldBegin('groupByInput', Thrift.Type.STRUCT, 7);
    this.groupByInput.write(output);
    output.writeFieldEnd();
  }
  if (this.getDataDictInput !== null && this.getDataDictInput !== undefined) {
    output.writeFieldBegin('getDataDictInput', Thrift.Type.STRUCT, 8);
    this.getDataDictInput.write(output);
    output.writeFieldEnd();
  }
  if (this.editColInput !== null && this.editColInput !== undefined) {
    output.writeFieldBegin('editColInput', Thrift.Type.STRUCT, 9);
    this.editColInput.write(output);
    output.writeFieldEnd();
  }
  if (this.resultSetAbsoluteInput !== null && this.resultSetAbsoluteInput !== undefined) {
    output.writeFieldBegin('resultSetAbsoluteInput', Thrift.Type.STRUCT, 10);
    this.resultSetAbsoluteInput.write(output);
    output.writeFieldEnd();
  }
  if (this.freeResultSetInput !== null && this.freeResultSetInput !== undefined) {
    output.writeFieldBegin('freeResultSetInput', Thrift.Type.STRUCT, 11);
    this.freeResultSetInput.write(output);
    output.writeFieldEnd();
  }
  if (this.deleteTableInput !== null && this.deleteTableInput !== undefined) {
    output.writeFieldBegin('deleteTableInput', Thrift.Type.STRUCT, 12);
    this.deleteTableInput.write(output);
    output.writeFieldEnd();
  }
  if (this.getTableRefCountInput !== null && this.getTableRefCountInput !== undefined) {
    output.writeFieldBegin('getTableRefCountInput', Thrift.Type.STRUCT, 13);
    this.getTableRefCountInput.write(output);
    output.writeFieldEnd();
  }
  if (this.listTablesInput !== null && this.listTablesInput !== undefined) {
    output.writeFieldBegin('listTablesInput', Thrift.Type.STRING, 14);
    output.writeString(this.listTablesInput);
    output.writeFieldEnd();
  }
  if (this.bulkDeleteTablesInput !== null && this.bulkDeleteTablesInput !== undefined) {
    output.writeFieldBegin('bulkDeleteTablesInput', Thrift.Type.STRING, 15);
    output.writeString(this.bulkDeleteTablesInput);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiOutputT = function(args) {
  this.statusOutput = null;
  this.statOutput = null;
  this.listTablesOutput = null;
  this.makeResultSetOutput = null;
  this.resultSetNextOutput = null;
  this.countOutput = null;
  this.getDataDictOutput = null;
  this.bulkLoadOutput = null;
  this.getTableRefCountOutput = null;
  this.deleteTablesOutput = null;
  this.joinOutput = null;
  if (args) {
    if (args.statusOutput !== undefined) {
      this.statusOutput = args.statusOutput;
    }
    if (args.statOutput !== undefined) {
      this.statOutput = args.statOutput;
    }
    if (args.listTablesOutput !== undefined) {
      this.listTablesOutput = args.listTablesOutput;
    }
    if (args.makeResultSetOutput !== undefined) {
      this.makeResultSetOutput = args.makeResultSetOutput;
    }
    if (args.resultSetNextOutput !== undefined) {
      this.resultSetNextOutput = args.resultSetNextOutput;
    }
    if (args.countOutput !== undefined) {
      this.countOutput = args.countOutput;
    }
    if (args.getDataDictOutput !== undefined) {
      this.getDataDictOutput = args.getDataDictOutput;
    }
    if (args.bulkLoadOutput !== undefined) {
      this.bulkLoadOutput = args.bulkLoadOutput;
    }
    if (args.getTableRefCountOutput !== undefined) {
      this.getTableRefCountOutput = args.getTableRefCountOutput;
    }
    if (args.deleteTablesOutput !== undefined) {
      this.deleteTablesOutput = args.deleteTablesOutput;
    }
    if (args.joinOutput !== undefined) {
      this.joinOutput = args.joinOutput;
    }
  }
};
XcalarApiOutputT.prototype = {};
XcalarApiOutputT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.statusOutput = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.statOutput = new XcalarApiGetStatOutputT();
        this.statOutput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.listTablesOutput = new XcalarApiListTablesOutputT();
        this.listTablesOutput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRUCT) {
        this.makeResultSetOutput = new XcalarApiMakeResultSetOutputT();
        this.makeResultSetOutput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRUCT) {
        this.resultSetNextOutput = new XcalarApiResultSetNextOutputT();
        this.resultSetNextOutput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.STRUCT) {
        this.countOutput = new XcalarApiCountOutputT();
        this.countOutput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRUCT) {
        this.getDataDictOutput = new XcalarApiGetDataDictOutputT();
        this.getDataDictOutput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.STRUCT) {
        this.bulkLoadOutput = new XcalarApiNewTableOutputT();
        this.bulkLoadOutput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 9:
      if (ftype == Thrift.Type.STRUCT) {
        this.getTableRefCountOutput = new XcalarApiGetTableRefCountOutputT();
        this.getTableRefCountOutput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 10:
      if (ftype == Thrift.Type.STRUCT) {
        this.deleteTablesOutput = new XcalarApiBulkDeleteTablesOutputT();
        this.deleteTablesOutput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 11:
      if (ftype == Thrift.Type.STRUCT) {
        this.joinOutput = new XcalarApiNewTableOutputT();
        this.joinOutput.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiOutputT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiOutputT');
  if (this.statusOutput !== null && this.statusOutput !== undefined) {
    output.writeFieldBegin('statusOutput', Thrift.Type.I32, 1);
    output.writeI32(this.statusOutput);
    output.writeFieldEnd();
  }
  if (this.statOutput !== null && this.statOutput !== undefined) {
    output.writeFieldBegin('statOutput', Thrift.Type.STRUCT, 2);
    this.statOutput.write(output);
    output.writeFieldEnd();
  }
  if (this.listTablesOutput !== null && this.listTablesOutput !== undefined) {
    output.writeFieldBegin('listTablesOutput', Thrift.Type.STRUCT, 3);
    this.listTablesOutput.write(output);
    output.writeFieldEnd();
  }
  if (this.makeResultSetOutput !== null && this.makeResultSetOutput !== undefined) {
    output.writeFieldBegin('makeResultSetOutput', Thrift.Type.STRUCT, 4);
    this.makeResultSetOutput.write(output);
    output.writeFieldEnd();
  }
  if (this.resultSetNextOutput !== null && this.resultSetNextOutput !== undefined) {
    output.writeFieldBegin('resultSetNextOutput', Thrift.Type.STRUCT, 5);
    this.resultSetNextOutput.write(output);
    output.writeFieldEnd();
  }
  if (this.countOutput !== null && this.countOutput !== undefined) {
    output.writeFieldBegin('countOutput', Thrift.Type.STRUCT, 6);
    this.countOutput.write(output);
    output.writeFieldEnd();
  }
  if (this.getDataDictOutput !== null && this.getDataDictOutput !== undefined) {
    output.writeFieldBegin('getDataDictOutput', Thrift.Type.STRUCT, 7);
    this.getDataDictOutput.write(output);
    output.writeFieldEnd();
  }
  if (this.bulkLoadOutput !== null && this.bulkLoadOutput !== undefined) {
    output.writeFieldBegin('bulkLoadOutput', Thrift.Type.STRUCT, 8);
    this.bulkLoadOutput.write(output);
    output.writeFieldEnd();
  }
  if (this.getTableRefCountOutput !== null && this.getTableRefCountOutput !== undefined) {
    output.writeFieldBegin('getTableRefCountOutput', Thrift.Type.STRUCT, 9);
    this.getTableRefCountOutput.write(output);
    output.writeFieldEnd();
  }
  if (this.deleteTablesOutput !== null && this.deleteTablesOutput !== undefined) {
    output.writeFieldBegin('deleteTablesOutput', Thrift.Type.STRUCT, 10);
    this.deleteTablesOutput.write(output);
    output.writeFieldEnd();
  }
  if (this.joinOutput !== null && this.joinOutput !== undefined) {
    output.writeFieldBegin('joinOutput', Thrift.Type.STRUCT, 11);
    this.joinOutput.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiWorkItemT = function(args) {
  this.apiVersion = null;
  this.api = null;
  this.input = null;
  if (args) {
    if (args.apiVersion !== undefined) {
      this.apiVersion = args.apiVersion;
    }
    if (args.api !== undefined) {
      this.api = args.api;
    }
    if (args.input !== undefined) {
      this.input = args.input;
    }
  }
};
XcalarApiWorkItemT.prototype = {};
XcalarApiWorkItemT.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.apiVersion = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.api = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.input = new XcalarApiInputT();
        this.input.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiWorkItemT.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiWorkItemT');
  if (this.apiVersion !== null && this.apiVersion !== undefined) {
    output.writeFieldBegin('apiVersion', Thrift.Type.I32, 1);
    output.writeI32(this.apiVersion);
    output.writeFieldEnd();
  }
  if (this.api !== null && this.api !== undefined) {
    output.writeFieldBegin('api', Thrift.Type.I32, 2);
    output.writeI32(this.api);
    output.writeFieldEnd();
  }
  if (this.input !== null && this.input !== undefined) {
    output.writeFieldBegin('input', Thrift.Type.STRUCT, 3);
    this.input.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

XcalarApiWorkItemResult = function(args) {
  this.jobStatus = null;
  this.output = null;
  if (args) {
    if (args.jobStatus !== undefined) {
      this.jobStatus = args.jobStatus;
    }
    if (args.output !== undefined) {
      this.output = args.output;
    }
  }
};
XcalarApiWorkItemResult.prototype = {};
XcalarApiWorkItemResult.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.jobStatus = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.output = new XcalarApiOutputT();
        this.output.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

XcalarApiWorkItemResult.prototype.write = function(output) {
  output.writeStructBegin('XcalarApiWorkItemResult');
  if (this.jobStatus !== null && this.jobStatus !== undefined) {
    output.writeFieldBegin('jobStatus', Thrift.Type.I32, 1);
    output.writeI32(this.jobStatus);
    output.writeFieldEnd();
  }
  if (this.output !== null && this.output !== undefined) {
    output.writeFieldBegin('output', Thrift.Type.STRUCT, 2);
    this.output.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

