//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


OperatorsOpT = {
'OperatorsMax' : 0,
'OperatorsMin' : 1,
'OperatorsSumKeys' : 2,
'OperatorsCountKeys' : 3,
'OperatorsAverage' : 4,
'OperatorsEqual' : 5,
'OperatorsLess' : 6,
'OperatorsMore' : 7,
'OperatorsLessEqual' : 8,
'OperatorsMoreEqual' : 9,
'OperatorsNotEqual' : 10,
'OperatorsUnique' : 11,
'OperatorsNotUnique' : 12,
'OperatorsRegex' : 13,
'OperatorsLeftOuterJoin' : 14,
'OperatorsInnerJoin' : 15
};
OperatorsOpTStr = {0 : 'OperatorsMax',
1 : 'OperatorsMin',
2 : 'OperatorsSumKeys',
3 : 'OperatorsCountKeys',
4 : 'OperatorsAverage',
5 : 'OperatorsEqual',
6 : 'OperatorsLess',
7 : 'OperatorsMore',
8 : 'OperatorsLessEqual',
9 : 'OperatorsMoreEqual',
10 : 'OperatorsNotEqual',
11 : 'OperatorsUnique',
12 : 'OperatorsNotUnique',
13 : 'OperatorsRegex',
14 : 'OperatorsLeftOuterJoin',
15 : 'OperatorsInnerJoin'
};
