//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
'XcalarApiVersionSignature' : 151027139
};
XcalarApiVersionTStr = {151027139 : '9007dc3a19f37fc5eb789a3cb61d0954'
};
