//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
'XcalarApiVersionSignature' : 266499596
};
XcalarApiVersionTStr = {266499596 : 'fe2760cca59ba0dc63f0e309dec9cfc1'
};
