//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
'XcalarApiVersionSignature' : 263379475
};
XcalarApiVersionTStr = {263379475 : 'fb2da1388629b9cce084c25475cc2160'
};
