//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


JoinOperatorT = {
  'InnerJoin' : 0,
  'LeftOuterJoin' : 1,
  'RightOuterJoin' : 2,
  'FullOuterJoin' : 3,
  'CrossJoin' : 4
};
JoinOperatorTStr = {
  0 : 'innerJoin',
  1 : 'leftJoin',
  2 : 'rightJoin',
  3 : 'fullOuterJoin',
  4 : 'crossJoin'
};
JoinOperatorTFromStr = {
  'innerJoin' : 0,
  'leftJoin' : 1,
  'rightJoin' : 2,
  'fullOuterJoin' : 3,
  'crossJoin' : 4
};
