//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
  'XcalarApiVersionSignature' : 11562885
};
XcalarApiVersionTStr = {
  11562885 : '0b06f85a9e082a5264379b84de8f3968'
};
XcalarApiVersionTFromStr = {
  '0b06f85a9e082a5264379b84de8f3968' : 11562885
};
