//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarEvalArgTypeT = {
  'OptionalArg' : 0,
  'RequiredArg' : 1,
  'VariableArg' : 2
};
XcalarEvalArgTypeTStr = {
  0 : 'optional',
  1 : 'required',
  2 : 'variable'
};
XcalarEvalArgTypeTFromStr = {
  'optional' : 0,
  'required' : 1,
  'variable' : 2
};
