//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarEvalArgTypeT = {
  'OptionalArg' : 0,
  'RequiredArg' : 1,
  'VariableArg' : 2
};
AccumulatorTypeT = {
  'AccumulatorMax' : 0,
  'AccumulatorMin' : 1,
  'AccumulatorSum' : 2,
  'AccumulatorCount' : 3,
  'AccumulatorAvg' : 4
};
XcalarEvalArgTypeTStr = {
  0 : 'optional',
  1 : 'required',
  2 : 'variable'
};
XcalarEvalArgTypeTFromStr = {
  'optional' : 0,
  'required' : 1,
  'variable' : 2
};
AccumulatorTypeTStr = {
  0 : 'max',
  1 : 'min',
  2 : 'sum',
  3 : 'count',
  4 : 'avg'
};
AccumulatorTypeTFromStr = {
  'max' : 0,
  'min' : 1,
  'sum' : 2,
  'count' : 3,
  'avg' : 4
};
