//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
  'XcalarApiVersionSignature' : 220316447
};
XcalarApiVersionTStr = {
  220316447 : 'd21c31f5183afc6d2f6b287f8a45e899'
};
XcalarApiVersionTFromStr = {
  'd21c31f5183afc6d2f6b287f8a45e899' : 220316447
};
