//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
  'XcalarApiVersionSignature' : 57828921
};
XcalarApiVersionTStr = {
  57828921 : '3726639cbe6e83efe9d2e95ecb57471f'
};
XcalarApiVersionTFromStr = {
  '3726639cbe6e83efe9d2e95ecb57471f' : 57828921
};
