import { expect } from 'chai'

describe('FileBrowser2 Test', () => {


    before(async () => {

    });

    after(async () => {
    });

    /**
     * Check metadata tables generated by discover_all
     */
    it ('first test', () => {
        expect(5 + 2).to.equal(7)
    });

});
