declare var StatusBox;
declare var PTblManager;
declare var xcHelper;
declare var xcUIHelper;
declare var PatternCategory;
declare var PatternAction;
declare var xcStringHelper;
declare var LoadScreen;
declare var DSTargetManager;
declare var Alert;
declare var HomeScreen;
declare var UrlToTab;
declare var DragDropUploader;
declare var UploadTStr;
declare var PromiseHelper;
declare var CloudFileBrowser;
declare var Xcrpc;
declare var Transaction;

declare function XcalarListFiles(param: any): any;