//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


AggregateOperatorT = {
'AggrMax' : 0,
'AggrMin' : 1,
'AggrSumKeys' : 2,
'AggrCountKeys' : 3,
'AggrAverage' : 4
};
AggregateOperatorTStr = {0 : 'max',
1 : 'min',
2 : 'sum',
3 : 'count',
4 : 'avg'
};
