//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


DgDagStateT = {
  'DgDagStateUnknown' : 0,
  'DgDagStateCreated' : 1,
  'DgDagStateQueued' : 2,
  'DgDagStateProcessing' : 3,
  'DgDagStateCleaned' : 4,
  'DgDagStateReady' : 5,
  'DgDagStateDropped' : 6,
  'DgDagStateError' : 7
};
DgDagStateTStr = {0 : 'DgDagStateUnknown',
1 : 'DgDagStateCreated',
2 : 'DgDagStateQueued',
3 : 'DgDagStateProcessing',
4 : 'DgDagStateCleaned',
5 : 'DgDagStateReady',
6 : 'DgDagStateDropped',
7 : 'DgDagStateError'
};
