//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


DsTargetTypeT = {
  'DsTargetUnknownType' : 0,
  'DsTargetODBCType' : 1,
  'DsTargetSFType' : 2
};
DsExportCreateRuleT = {
  'DsExportUnknownRule' : 0,
  'DsExportCreateOnly' : 1,
  'DsExportCreateOrAppend' : 2,
  'DsExportAppendOnly' : 3,
  'DsExportDeleteAndReplace' : 4
};
DsTargetTypeTStr = {0 : 'unknown',
1 : 'odbc',
2 : 'file'
};
DsExportCreateRuleTStr = {0 : 'unknown',
1 : 'createOnly',
2 : 'createOrAppend',
3 : 'appendOnly',
4 : 'deleteAndReplace'
};
