//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


FunctionCategoryT = {
  'CategoryArithmetic' : 0,
  'CategoryBitwise' : 1,
  'CategoryTrigonometry' : 2,
  'CategoryConversion' : 3,
  'CategoryMisc' : 4,
  'CategoryCondition' : 5,
  'CategoryAggregate' : 6
};
FunctionCategoryTStr = {0 : 'Arithmetic functions',
1 : 'Bitwise functions',
2 : 'Trigonometric functions',
3 : 'Conversion functions',
4 : 'Miscellaneous functions',
5 : 'Conditional functions',
6 : 'Aggregate functions'
};
