//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


FunctionCategoryT = {
  'FunctionCategoryArithmetic' : 0,
  'FunctionCategoryBitwise' : 1,
  'FunctionCategoryTrigonometry' : 2,
  'FunctionCategoryConversion' : 3,
  'FunctionCategoryMisc' : 4,
  'FunctionCategoryCondition' : 5,
  'FunctionCategoryAggregate' : 6
};
FunctionCategoryTStr = {0 : 'Arithmetic functions',
1 : 'Bitwise functions',
2 : 'Trigonometric functions',
3 : 'Conversion functions',
4 : 'Miscellaneous functions',
5 : 'Conditional functions',
6 : 'Aggregate functions'
};

