//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


JoinOperatorT = {
'InnerJoin' : 0,
'LeftOuterJoin' : 1,
'RightOuterJoin' : 2,
'FullOuterJoin' : 3
};
JoinOperatorTStr = {
0 : 'innerJoin',
1 : 'leftJoin',
2 : 'rightJoin',
3 : 'fullOuterJoin'
};
