//
// **********************************************************************
// *** DO NOT EDIT!  This file was autogenerated by genenum.py        ***
// *** Please edit LibApisConstants.enum instead
// **********************************************************************
//
// Copyright 2014 Xcalar, Inc. All rights reserved.
//
// No use, or distribution, of this source code is permitted in any form or
// means without a valid, written license agreement with Xcalar, Inc.
// Please refer to the included "COPYING" file for terms and conditions
// regarding the use and redistribution of this software.
//
// **********************************************************************
// *** DO NOT EDIT!  This file was autogenerated by genenum.py        ***
// *** Please edit LibApisConstants.enum instead
// **********************************************************************
//

enum XcalarApisConstantsT {
    XcalarApiMaxEvalStringLen = 1024,
    XcalarApiMaxNumParameters = 20,
}

const map<XcalarApisConstantsT,string> XcalarApisConstantsTStr = {
    XcalarApisConstantsT.XcalarApiMaxEvalStringLen:"XcalarApiMaxEvalStringLen",
    XcalarApisConstantsT.XcalarApiMaxNumParameters:"XcalarApiMaxNumParameters",
}

