//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


SourceTypeT = {
  'SrcUnknown' : 0,
  'SrcDataset' : 1,
  'SrcTable' : 2,
  'SrcConstant' : 3,
  'SrcExport' : 4
};
SourceTypeTStr = {0 : 'Unknown',
1 : 'Dataset',
2 : 'Table',
3 : 'Constant',
4 : 'Export'
};
