//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
  'XcalarApiVersionSignature' : 66155739
};
XcalarApiVersionTStr = {66155739 : '3f174dbf9ecd6364148c51b47400a2f9'
};
