//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
'XcalarApiVersionSignature' : 54520027
};
XcalarApiVersionTStr = {54520027 : '33fe8db67bee195984433f49cc1a403d'
};
