//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
'XcalarApiVersionSignature' : 24759135
};
XcalarApiVersionTStr = {24759135 : '179cb5f393a4c3540299a16b6808575d'
};
