class DagNodeMap extends DagNode {
    protected input: DagNodeMapInput;

    public constructor(options: DagNodeInfo) {
        super(options);
        this.type = DagNodeType.Map;
        this.allowAggNode = true;
        this.minParents = 1;
    }

    /**
     * @returns {DagNodeMapInput} Map node parameters
     */
    public getParam(): DagNodeMapInput {
        return {
            eval: this.input.eval || [{evalString: "", newField: ""}],
            icv: this.input.icv || false
        };
    }

    /**
     * Set map node's parameters
     * @param input {DagNodeMapInput}
     * @param input.eval {Array} array of {evalString, newFieldName}
     */
    public setParam(input: DagNodeMapInput = <DagNodeMapInput>{}) {
        this.input = {
            eval: input.eval,
            icv: input.icv
        }
        super.setParam();
    }

    public lineageChange(columns: ProgCol[]): DagLineageChange {
        const changes: {from: ProgCol, to: ProgCol}[] = [];
        this.input.eval.forEach((evalInput) => {
            const colName: string = evalInput.newField;
            if (xcHelper.parsePrefixColName(colName).prefix) {
                throw new Error("columns generated by map cannot have prefix");
            }

            const colType: ColumnType = this._getOpType(evalInput.evalString);
            const progCol = ColManager.newPullCol(colName, colName, colType);
            columns.push(progCol);
            changes.push({
                from: null,
                to: progCol
            });
        });
        return {
            columns: columns,
            changes: changes
        };
    }

    private _getOpType(evalStr: string): ColumnType {
        // XXX TODO, use g4 to parse it
        const operator: string = evalStr.substring(0, evalStr.indexOf("("));
        let colType: ColumnType = null;
        const opsMap = XDFManager.Instance.getOperatorsMap();
        for (let category in opsMap) {
            const ops = opsMap[category];
            ops.forEach((opInfo) => {
                if (opInfo.fnName === operator) {
                    colType = xcHelper.getDFFieldTypeToString(opInfo.outputType);
                    return false; // stop second-level loop
                }
            });

            if (colType != null) {
                break; // stop first-level loop
            }
        }
        return colType;
    }
}