var paths = {
    dologout: 'assets/htmlFiles/dologout.html',
    login: 'assets/htmlFiles/login.html',
    cloudLogin: 'cloudLogin/cloudLogin.html',
    tableau: 'assets/htmlFiles/tableau.html',
    indexAbsolute: "/index.html",
    index: 'index.html',
    testAbsolute: '/unitTest.html',
    workbookTut: 'assets/htmlFiles/walk/workbookTut.html',
    datasetPanelTutA1: 'assets/htmlFiles/walk/datasetPanelTutA1.html',
    importDatasourceTutA2: 'assets/htmlFiles/walk/importDatasourceTutA2.html',
    browseDatasourceTutA3: 'assets/htmlFiles/walk/browseDatasourceTutA3.html',
    browseDatasource2TutA4: 'assets/htmlFiles/walk/browseDatasource2TutA4.html',
    datastoreTut1: 'assets/htmlFiles/walk/datastoreTut1.html',
    datastoreTut2: 'assets/htmlFiles/walk/datastoreTut2.html',
    waitIcon: 'assets/images/waiting-1.gif',
    loadBarIcon: "assets/images/loading-bar.gif",
    XCExt: 'assets/images/extension/logo-xc.png',
    XDExt: 'assets/images/extension/logo-xd.png',
    CustomExt: 'assets/images/extension/logo-custom.png',
    tableauExt: 'assets/images/extension/logo-tableau.png',
    helpUserGuide: 'assets/help/user/Content/Home.htm',
    helpUserContent: 'assets/help/user/Content/',
    helpUserSearch: 'assets/help/user/Content/SearchInsight.htm?q=',
    favicon: "assets/images/xc-favicon.png",
    faviconUnsave: "assets/images/xc-favicon-unsave.gif",
    memory: "https://www.xcalar.com/documentation/help/XD/1.3.0/Content/C_AdvancedTasks/I_UnderstandMemoryUse.htm",
};
