var paths = {
    dologout: 'assets/htmlFiles/dologout.html',
    login: 'assets/htmlFiles/login.html',
    cloudLogin: 'cloudLogin/cloudLogin.html',
    indexAbsolute: "/index.html",
    index: 'index.html',
    testAbsolute: '/unitTest.html',
    waitIcon: 'assets/images/waiting-1.gif',
    loadBarIcon: "assets/images/loading-bar.gif",
    XDExt: 'assets/images/extension/logo-xd.png',
    helpUserGuide: 'assets/help/user/Content/Home.htm',
    helpUserContent: 'assets/help/user/Content/',
    helpUserSearch: 'assets/help/user/Content/SearchInsight.htm?q=',
    favicon: "assets/images/xc-favicon.png",
    faviconUnsave: "assets/images/xc-favicon-unsave.gif",
    memory: "https://www.xcalar.com/documentation/help/XD/1.3.0/Content/C_AdvancedTasks/I_UnderstandMemoryUse.htm",
};
