//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


GenericTypesRecordTypeT = {
'GenericTypesFixedSize' : 0,
'GenericTypesVariableSize' : 1
};
GenericTypesRecordTypeTStr = {0 : 'GenericTypesFixedSize',
1 : 'GenericTypesVariableSize'
};
