//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApisConstantsT = {
  'XcalarApiMaxEvalStringLen' : 1024,
  'XcalarApiMaxNumParameters' : 20,
  'XcalarApiDefaultTopIntervalInMs' : 100,
  'XcalarApiMaxPyModuleNameLen' : 255,
  'XcalarApiMaxPyFuncNameLen' : 255,
  'XcalarApiMaxPyErrorMsgLen' : 255,
  'XcalarApiMaxPyModuleSrcLen' : 10485760,
  'XcalarApiMaxTableNameLen' : 255,
  'XcalarApiMagic' : 37359285,
  'XcalarApiRetinaMaxNumTables' : 128
};
XcalarApisConstantsTStr = {1024 : 'XcalarApiMaxEvalStringLen',
20 : 'XcalarApiMaxNumParameters',
100 : 'XcalarApiDefaultTopIntervalInMs',
255 : 'XcalarApiMaxPyModuleNameLen',
255 : 'XcalarApiMaxPyFuncNameLen',
255 : 'XcalarApiMaxPyErrorMsgLen',
10485760 : 'XcalarApiMaxPyModuleSrcLen',
255 : 'XcalarApiMaxTableNameLen',
37359285 : 'XcalarApiMagic',
128 : 'XcalarApiRetinaMaxNumTables'
};
