//
// Autogenerated by Thrift Compiler (0.9.1)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApisConstantsT = {
'XcalarApiMaxEvalStringLen' : 1024,
'XcalarApiMaxNumParameters' : 20
};
XcalarApisConstantsTStr = {1024 : 'XcalarApiMaxEvalStringLen',
20 : 'XcalarApiMaxNumParameters'
};
