//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarOrderingT = {
  'XcalarOrderingUnordered' : 0,
  'XcalarOrderingAscending' : 3,
  'XcalarOrderingDescending' : 5,
  'XcalarOrderingInvalid' : 65534
};
XcalarOrderingTStr = {0 : 'Unordered',
3 : 'Ascending',
5 : 'Descending',
65534 : 'Invalid'
};
