//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


QueryStateT = {
  'qrNotStarted' : 0,
  'qrProcssing' : 1,
  'qrFinished' : 2,
  'qrError' : 3
};
QueryStateTStr = {0 : 'qrNotStarted',
1 : 'qrProcssing',
2 : 'qrFinished',
3 : 'qrError'
};
