//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


SourceTypeT = {
  'SrcUnknown' : 0,
  'SrcDataset' : 1,
  'SrcTable' : 2,
  'SrcConstant' : 3
};
SourceTypeTStr = {0 : 'SrcUnknown',
1 : 'SrcDataset',
2 : 'SrcTable',
3 : 'SrcConstant'
};
