//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
  'XcalarApiVersionSignature' : 229301989
};
XcalarApiVersionTStr = {229301989 : 'daadee5d81984808824ca1d6a2204053'
};
