//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
  'XcalarApiVersionSignature' : 136099753
};
XcalarApiVersionTStr = {136099753 : '81cb7a984dbec7361bdc61e2191d817c'
};
