//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


XcalarApiVersionT = {
  'XcalarApiVersionSignature' : 173141960
};
XcalarApiVersionTStr = {173141960 : 'a51efc83c2785ab651c4c3e65e6e25f1'
};
